require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'example' do
  platform :ios, '11.0'

  config = use_native_modules!

  pod 'react-native-usercentrics', :path => '../..'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

    target 'exampleTests' do
        inherit! :complete
    end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
